<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: nolic
 * Date: Mon, 06 Jul 2020 16:55:36 +0200
 */

$conf['title'] = 'Шахты - тест';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'nolic';
$conf['proxy']['pass'] = '<b>NzQxMjU4ODk=';
