# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 06 Jul 2020 14:54:21 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

nolic:$1$5CwySFFd$3dg4KY0VtSKV5W8WO/AVE1:nolic:nikch3008@mail.ru:admin,user
